apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: namespace1
  labels:
    name: test-pod
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "64Mi"
          cpu: "200m"
      ports:
        - containerPort: 80