apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: prod
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx
        name: nginx-img