apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  color: {{ .Values.data.color | default "pink" }}
  size: {{ .Values.data.size | upper | quote }}
  {{ if eq .Values.data.lenght "lenght" }} lenght: {{ .Values.data.lenght | quote }} {{ end }}